### PR TITLE
Added an appcast generator

### PR DESCRIPTION
**Pull request by ndreisg**
#52

### CODE REVIEW

**Comment by Deadpikle** [comment]
Thanks @ndreisg! :) I will take a look at this in the next few days more seriously, but at first glance, please use 4 spaces instead of 2 so that this code matches the rest of the project. Thank!

**Comment by Deadpikle** [comment]
Hi again. In general, looks good. Would like to request a couple additions/changes:

* Add `sparkle:os="windows"` to all app cast items
* I would like the `*.priv` path to be passed in via command line, not located in the folder with the `.exe` files. This makes it so that you can just upload the folder with EXE and appcast to your server without worrying about accidentally including your `*.priv` file.
* Could you refactor DSA generation to `NetSparkle.Utilities` (avail in the latest commit) and also update `NetSparkleDSAHelper` to use the same function? That way we don't have multiple  implementations for hashing if we decide to need to update it in the future (macOS Sparkle recently updated to `EdDSA`. This will also save some repeated code in `Program.cs`.
* To generate the appcast with multiple exes, you need to rewrite the loop as follows (as right now you write the appcast on every exe...):
```

// TODO: get first product's version info to get the product name OR pass this in via command line
// currently this won't compile
var appCastGenerator = new AppCastXMLGenerator(versionInfo.ProductName);

foreach (var exePath in exePaths)
{
    String dsaSignature = "";

    if (cryptoProvider != null) // TODO: replace with function
    {
        // open stream
        Byte[] hash = null;
        using (Stream inputStream = File.OpenRead(exePath))
        {
            hash = cryptoProvider.SignData(inputStream);
        }

        dsaSignature = Convert.ToBase64String(hash);
    }

    var versionInfo = FileVersionInfo.GetVersionInfo(exePath);
    var fileInfo = new FileInfo(exePath);
    appCastGenerator.AddItem(
        new AppCastXMLItem(versionInfo.ProductVersion, 
        Path.GetFileName(versionInfo.FileName), 
        versionInfo.ProductVersion, 
        fileInfo.CreationTime, 
        length: fileInfo.Length.ToString(), 
        dsaSignature: dsaSignature)
    );
}

var appcastXmlDocument = appCastGenerator.GenerateAppCast();
appcastXmlDocument.Save("appcast.xml");
if (cryptoProvider != null) // TODO: replace with function
{
    // open stream
    Byte[] hash = null;
    using (Stream inputStream = File.OpenRead("appcast.xml"))
    {
        hash = cryptoProvider.SignData(inputStream);
    }

    dsaSignature = Convert.ToBase64String(hash);
    File.WriteAllText("appcast.xml.dsa", dsaSignature);
}
```
I added some TODO for that loop as well.

Future notes that don't need to be implemented in this PR but that I want to remember:
* Do you have any thoughts on how to support `sparkle:criticalUpdate`? Perhaps we could optionally pass in a file that maps exe or version to whether updates are critical or not.
* Any thoughts on how to add release note links? Probably could point to a folder of files (*.md or *.txt) that have the same file name as the version number of the exe or something.
* We'll want to integrate unit tests here at some point as we move forward to a 2.0


Thanks again!

**Comment by Deadpikle** [comment]
Re: Sending in the `*.priv` file via command line:

Would like the command line params order to match Sparkle for macOS: `generate_appcast <private key path> <directory with update archives>`

**Comment by ndreisg** [comment]
The last commits are untested. I will test it on Monday at work.

**Comment by ndreisg** [comment]
Another thing I shortly realised:

generate_appcast on macOS seems to use SUFeedURL to generate the URLs for the enclosures.
It just assumes, that the update files and the appcast.xml will be in the same directory.

On windows I can't do this, so I'm currently just using the filename and extension as url.

Probably it would be possible to use _appCastUrl, remove the xml file name and prepend this to the enclosures url attribute when the AppCastItems are read.

**Comment by Deadpikle** [comment]
I'll wait to look at/comment on code until you've had a chance to test it yourself. 😄 

As far as `SUFeedURL` goes, that's a good default I think. We could add an optional command line parameter for the URL base such that the URL then becomes `"https://example.com/" + folderName + "/" + fileName` or similar. 🤔

**Comment by ndreisg** [comment]
I tested my changes and everything seems to be working :)
Download URLs are now completed with appcast URL if they only contain a filename.

The base URL parameter is a good idea, but I wouldn't include the 'folderName'.
I am generating the appcast on a network drive, our webmaster later uploads the new files to our website. The foldername in the network drive and in the URL do not match in my case.

> Do you have any thoughts on how to support sparkle:criticalUpdate? Perhaps we could optionally pass in a file that maps exe or version to whether updates are critical or not.

> Any thoughts on how to add release note links? Probably could point to a folder of files (*.md or *.txt) that have the same file name as the version number of the exe or something.

For both cases I would suggest a JSON file next to the exe with the same name.
eg. for "MyApp_1.0.exe" you would create a "MyApp_1.0.json" next to it.
This JSON file could then contain something like this:

{
  "critical": true,
  "releaseNotesLink": "..."
}

**Comment by ndreisg** [comment]
Regarding the base URL param:
It's getting pretty complicated to parse the params since most of them are optional.
I would suggest to switch to a notation like the following:

`generate_appcast [/K <path_to_private_key>] /D <directory_with_update_files> [/S <search_pattern>] [/U <base_url>]`

The order of the params would be irrelevant in that case and parsing would be much easyer.

**Comment by ndreisg** [comment]
I managed to keep the notation for the first two params and introduced '/' notation for the other two.

Usage:
  generate_appcast [<path_to_private_key>] <directory_with_update_files> [Options]

Options:
  /S <search_pattern>
  /U <base_url>

**Comment by Deadpikle** [comment]
@ndreisg 

Thank you for your noteworthy and great contribution! I have merged it in to the existing codebase and am working on updating NuGet and things now. I'll throw this into the NetSparkle.New.Extras NuGet package for now.

**Comment by ndreisg** [comment]
You are welcome. It was a pleasure :)

**Pull request merged**
